spring.application.name=Hotel-Andino-Plaza
# Configuración de la Base de Datos (MySQL en Puerto 3006)
spring.datasource.url=jdbc:mysql://localhost:3306/hotelandinoplaza?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Configuración del Servidor
server.port=8080